import { createContext,useContext,useEffect,useState } from "react";
import { supabase } from "../lib/supabase";
import { defaultContent,mergeContent } from "./defaultContent";
const CmsContext=createContext({content:defaultContent,loading:true,source:"fallback"});
export const useCms=()=>useContext(CmsContext);
const norm=(v)=>v.replace(/\s+/g," ").trim();
function derived(content){const text={...(content.textOverrides||{})},images={...(content.imageOverrides||{})},links={};const walk=(a,b)=>{if(typeof a==="string"&&typeof b==="string"&&a!==b){if(a.startsWith("/assets/"))images[a]=b;else if(/^(https?:|mailto:|#)/.test(a))links[a]=b;else text[norm(a)]=b}else if(a&&b&&typeof a==="object"&&typeof b==="object")Object.keys(a).forEach(k=>walk(a[k],b[k]))};walk(defaultContent,content);return{text,images,links}}
function applyOverrides(content){const maps=derived(content);const apply=()=>{document.querySelectorAll("img[src]").forEach(img=>{const original=img.dataset.cmsOriginalSrc||img.getAttribute("src");img.dataset.cmsOriginalSrc=original;if(maps.images[original])img.src=maps.images[original]});document.querySelectorAll("a[href]").forEach(a=>{const original=a.dataset.cmsOriginalHref||a.getAttribute("href");a.dataset.cmsOriginalHref=original;if(maps.links[original])a.href=maps.links[original]});const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode())){if(n.parentElement?.closest("[data-cms-ignore],script,style"))continue;const key=n.parentElement?.dataset.cmsOriginalText||norm(n.nodeValue||"");if(!key)continue;n.parentElement.dataset.cmsOriginalText=key;if(Object.prototype.hasOwnProperty.call(maps.text,key))n.nodeValue=n.nodeValue.replace(n.nodeValue.trim(),maps.text[key])}};apply();const o=new MutationObserver(apply);o.observe(document.body,{childList:true,subtree:true});return()=>o.disconnect()}
export function CmsProvider({children}){const[state,setState]=useState({content:defaultContent,loading:true,source:"fallback"});useEffect(()=>{let active=true;supabase.from("cms_documents").select("content").eq("id","site").eq("is_published",true).maybeSingle().then(({data,error})=>active&&setState({content:mergeContent(defaultContent,data?.content),loading:false,source:error||!data?"fallback":"supabase"})).catch(()=>active&&setState({content:defaultContent,loading:false,source:"fallback"}));return()=>{active=false}},[]);useEffect(()=>applyOverrides(state.content),[state.content]);return <CmsContext.Provider value={state}>{children}</CmsContext.Provider>}
